### ISSUE TITLE
About Execute Assembly..

### ISSUE THREAD

**Issue by ghost** [vincent-coding/uGecko#5]
So as far as I can tell it's used to send the actual Assembly Bytes located beneath  `C00000XX 60000000` codes. For example taking this simple Execute Assembly write..

```
C0000005 60000000
3D40109C 3D20010F
614AD8E4 61296AE0
814A0000 7D2903A6
39000000 812A00C0
91090934 4E800420
```

Then removing `C0000005 60000000` as the header leaving me with

```
3D40109C 3D20010F
614AD8E4 61296AE0
814A0000 7D2903A6
39000000 812A00C0
91090934 4E800420
```

So I take it I could then work these assembly bytes into a command like..

```python
gecko.executeAssembly('3D40109C3D20010F614AD8E461296AE0814A00007D2903A639000000812A00C0910909344E800420')
```

Would this be correct? Or am I misinterpreting the entire use of the function..

**Comment by Immortql** [comment]
I would also very much so like an answer to this question. Execute assembly is something I'd like to include in a few of my Python projects, but the documentation isn't clear on the format / use of the function.
